name: gatk
channels:
- conda-forge
- bioconda
- nodefaults
dependencies:
- bcftools >=1.23,<2
- joblib >=1.5.3,<2
- snakemake >=9.14.8,<10
- bwa >=0.7.19,<0.8
- samtools >=1.23,<2
- conda >=25.11.1,<26
- gatk4 >=4.6.2.0,<5

