[workspace]
authors = ["Charlie Simkin <charlie.simkin@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "gatk"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
bcftools = "*"
joblib = "*"
snakemake = "*"
bwa = "*"
samtools = "*"
conda = "*"
