[workspace]
authors = ["Charlie Simkin <charlie.simkin@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "gatk"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
gatk4 = "snakemake --unlock && snakemake -c 8 --rerun-incomplete"

[dependencies]
bcftools = ">=1.23,<2"
joblib = ">=1.5.3,<2"
snakemake = ">=7.32.4,<10"
bwa = ">=0.7.19,<0.8"
samtools = ">=1.23,<2"
conda = ">=25.11.1,<26"
gatk4 = ">=4.6.2.0,<5"
rsync = ">=3.4.1,<4"
snpeff = ">=5.4.0a,<6"

[feature.snpeff.dependencies]
snpeff = ">=5.4.0a,<6"

[environments]
snpeff = ['snpeff']
