[workspace]
authors = ["Charlie Simkin <charlie.simkin@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "gatk"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
snakemake = "snakemake -c 8"

[dependencies]
bcftools = ">=1.23,<2"
joblib = ">=1.5.3,<2"
snakemake = ">=9.14.8,<10"
bwa = ">=0.7.19,<0.8"
samtools = ">=1.23,<2"
conda = ">=25.11.1,<26"
gatk4 = ">=4.6.2.0,<5"
rsync = "*"
