[workspace]
authors = ["Charlie Simkin <charlie.simkin@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "gatk"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
snakemake = "snakemake -s draft_pipeline.smk -c 8 --use-conda"

[dependencies]
bcftools = "*"
joblib = "*"
snakemake = "9.1.*"
bwa = "*"
samtools = "*"
conda = "*"
