# Input Files
# ----------------------------------------------------------------------------------
genome_fasta: resources/PlasmoDB-62_Pfalciparum3D7_Genome.fasta
genome_gff: resources/PlasmoDB-62_Pfalciparum3D7.gff
known_sites_vcf: resources/known_sites.vcf.gz
targets_tsv: config/targets.tsv
sample_reads_folder: fastq_inputs
R1_suffix: _R1.fastq.gz
R2_suffix: _R2.fastq.gz

# Amplicon Sequencing
# If you used any form of amplicon sequencing (MIP, PCR, ..) then set the
# following to true
# ------------------------------------------------------------------------
amplicon_sequencing: true

# target mode to change based on whether you want to run haplotype caller with
# mutations from targeted only, novel discovery only, or consolidated with novel discovery
# and targeted together
target_mode: consolidated # novel, targeted, or consolidated

# number of base pairs surrounding your target to include
# most useful if you want to run in targeted mode but also include a window around your targets
# for novel discovery
interval_padding: 0 # integer representing base pairs surrounding target sites to include

# Output Files
# --------------------------------------------------------------------------
output_directory: results

# name and description of a snpEff database to be built
# ------------------------------------------------------------------------------------
genome_database_name: "plasmoDB_3D7_v62"
database_description: "A database for plasmoDB version 62"

# Directory of indexed input files
# if you have a globally accessible folder of indexed genome files and don't mind
# new indexes being added there, you can specify an absolute path to this
# directory. Otherwise, if you leave this variable as is it will create an
# indexed_input_files directory inside the current project directory.
# ---------------------------------------------------------------------------
indexed_input_directory: resources/indexed_input_files
