# Input Files
# ----------------------------------------------------------------------------------
genome_fasta: resources/PlasmoDB-62_Pfalciparum3D7_Genome.fasta
genome_gff: resources/PlasmoDB-62_Pfalciparum3D7.gff
known_sites_vcf: resources/known_sites.vcf.gz
targets_tsv: config/targets.tsv

sample_reads_folder: fastq_inputs
R1_suffix: _R1.fastq.gz
R2_suffix: _R2.fastq.gz

# Output Files
# --------------------------------------------------------------------------
output_directory: results/cherrypicked

# name and description of a snpEff database to be built
# ------------------------------------------------------------------------------------
genome_database_name: "plasmoDB_3D7_v62"
database_description: "A database for plasmoDB version 62"

# Directory of indexed input files
# if you have a globally accessible folder of indexed genome files and don't mind
# new indexes being added there, you can specify an absolute path to this
# directory. Otherwise, if you leave this variable as is it will create an
# indexed_input_files directory inside the current project directory.
# ---------------------------------------------------------------------------
indexed_input_directory: indexed_input_files
