ref_genome: /home/charlie/data/gatk4-illumina_test_data/PlasmoDB-62_Pfalciparum3D7_Genome.fasta
known_sites_vcf: /home/charlie/data/gatk4-illumina_test_data/known_sites.vcf.gz
targets_vcf: config/targets.vcf

output_directory: results
sample_reads_folder: /home/charlie/data/gatk4-illumina_test_data/cherrypicked_reads
samples_file: /home/charlie/data/gatk4-illumina_test_data/cherrypicked_reads/samples.txt
